/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project2.taskmaster;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author user85
 */
public class Homepage extends javax.swing.JPanel implements ActionListener {

    MainFrame frame;
    /**
     * Creates new form Homepage
     */
    public Homepage(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        
        homePanel = new javax.swing.JPanel();
        addTaskButton = new javax.swing.JButton();
        addTaskButton.addActionListener(this);
        viewTasksButton = new javax.swing.JButton();
        viewTasksButton.addActionListener(this);
        seeProfileButton = new javax.swing.JButton();
        seeProfileButton.addActionListener(this);
        exitButton = new javax.swing.JButton();
        exitButton.addActionListener(this);
        logoutBtn = new javax.swing.JButton();
        logoutBtn.addActionListener(this);

        addTaskPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saveTaskBtn = new javax.swing.JButton();
        saveTaskBtn.addActionListener(this);
        deltaskBtn = new javax.swing.JButton();
        deltaskBtn.addActionListener(this);
        addTaskgoHome = new javax.swing.JButton();
        addTaskTextArea = new javax.swing.JTextArea();
        addTaskgoHome.addActionListener(this);
        addTasksLogoutBtn = new javax.swing.JButton();
        addTasksLogoutBtn.addActionListener(this);
        addTasksExitBtn = new javax.swing.JButton();
        addTasksExitBtn.addActionListener(this);
        addTaskViewTasksBtn = new javax.swing.JButton();
        addTaskViewTasksBtn.addActionListener(this);
        
        viewTasksPane = new javax.swing.JPanel();
        task1Lbl = new javax.swing.JLabel();
        task2Lbl = new javax.swing.JLabel();
        task3Lbl = new javax.swing.JLabel();
        task4Lbl = new javax.swing.JLabel();
        viewTasksAddTaskBtn = new javax.swing.JButton();
        viewTasksAddTaskBtn.addActionListener(this);
        viewTasksExitBtn = new javax.swing.JButton();
        viewTasksExitBtn.addActionListener(this);
        viewTasksLogoutBtn = new javax.swing.JButton();
        viewTasksLogoutBtn.addActionListener(this);
        viewTasksgoHomeBtn = new javax.swing.JButton();
        viewTasksgoHomeBtn.addActionListener(this);
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profilePaneExitBtn = new javax.swing.JButton();
        profilePaneExitBtn.addActionListener(this);
        profilePaneLogoutBtn = new javax.swing.JButton();
        profilePaneLogoutBtn.addActionListener(this);
        profilePanegoHomeBtn = new javax.swing.JButton();
        profilePanegoHomeBtn.addActionListener(this);

        addTaskButton.setText("Add Task");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });

        viewTasksButton.setText("View Tasks");

        seeProfileButton.setText("Profile");

        exitButton.setText("Exit");

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(60, 60, 60)
                .addComponent(exitButton)
                .addGap(105, 105, 105))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seeProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(viewTasksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(addTaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(629, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(addTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(viewTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(seeProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Home", homePanel);

        addTaskTextArea.setColumns(20);
        addTaskTextArea.setRows(5);
        jScrollPane1.setViewportView(addTaskTextArea);

        saveTaskBtn.setText("save Task");
        saveTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTaskBtnActionPerformed(evt);
            }
        });

        deltaskBtn.setText("delete Task");

        addTaskgoHome.setText("home");

        addTasksLogoutBtn.setText("logout");

        addTasksExitBtn.setText("exit");
        addTasksExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTasksExitBtnActionPerformed(evt);
            }
        });

        addTaskViewTasksBtn.setText("view Tasks");
        addTaskViewTasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskViewTasksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTaskPanelLayout = new javax.swing.GroupLayout(addTaskPanel);
        addTaskPanel.setLayout(addTaskPanelLayout);
        addTaskPanelLayout.setHorizontalGroup(
            addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addTaskPanelLayout.createSequentialGroup()
                        .addComponent(addTaskgoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(saveTaskBtn)
                        .addGap(48, 48, 48)
                        .addComponent(deltaskBtn))
                    .addGroup(addTaskPanelLayout.createSequentialGroup()
                        .addComponent(addTaskViewTasksBtn)
                        .addGap(34, 34, 34)
                        .addComponent(addTasksLogoutBtn)
                        .addGap(33, 33, 33)
                        .addComponent(addTasksExitBtn)))
                .addGap(90, 90, 90))
        );
        addTaskPanelLayout.setVerticalGroup(
            addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveTaskBtn)
                    .addComponent(deltaskBtn)
                    .addComponent(addTaskgoHome))
                .addGap(18, 18, 18)
                .addGroup(addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTasksLogoutBtn)
                    .addComponent(addTasksExitBtn)
                    .addComponent(addTaskViewTasksBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Add Task", addTaskPanel);

        task1Lbl.setText("Task 1 ");

        task2Lbl.setText("Task 2");

        task3Lbl.setText("Task 3");

        task4Lbl.setText("Task 4");

        viewTasksAddTaskBtn.setText("Add Task");

        viewTasksExitBtn.setText("exit");

        viewTasksLogoutBtn.setText("logout");

        viewTasksgoHomeBtn.setText("home");

        jCheckBox1.setText("done");

        jCheckBox3.setText("done");

        jCheckBox4.setText("done");

        jCheckBox5.setText("done");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewTasksPaneLayout = new javax.swing.GroupLayout(viewTasksPane);
        viewTasksPane.setLayout(viewTasksPaneLayout);
        viewTasksPaneLayout.setHorizontalGroup(
            viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTasksPaneLayout.createSequentialGroup()
                .addGap(0, 490, Short.MAX_VALUE)
                .addComponent(viewTasksgoHomeBtn)
                .addGap(35, 35, 35)
                .addComponent(viewTasksLogoutBtn)
                .addGap(50, 50, 50)
                .addComponent(viewTasksExitBtn)
                .addGap(44, 44, 44))
            .addGroup(viewTasksPaneLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTasksAddTaskBtn)
                    .addGroup(viewTasksPaneLayout.createSequentialGroup()
                        .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(task1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(task2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(task3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(task4Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewTasksPaneLayout.setVerticalGroup(
            viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTasksPaneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(task1Lbl)
                    .addComponent(jCheckBox1))
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewTasksPaneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(task2Lbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTasksPaneLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jCheckBox4)))
                .addGap(18, 18, 18)
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(task3Lbl)
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(task4Lbl)
                    .addComponent(jCheckBox5))
                .addGap(83, 83, 83)
                .addComponent(viewTasksAddTaskBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(viewTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTasksExitBtn)
                    .addComponent(viewTasksLogoutBtn)
                    .addComponent(viewTasksgoHomeBtn))
                .addGap(40, 40, 40))
        );

        mainTabbedPane.addTab("View Task", viewTasksPane);

        jLabel1.setText("username");

        jLabel2.setText("password");

        jLabel3.setText("email");

        profilePaneExitBtn.setText("exit");
        profilePaneExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePaneExitBtnActionPerformed(evt);
            }
        });

        profilePaneLogoutBtn.setText("logout");

        profilePanegoHomeBtn.setText("home");
        profilePanegoHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePanegoHomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(540, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profilePanegoHomeBtn)
                .addGap(29, 29, 29)
                .addComponent(profilePaneLogoutBtn)
                .addGap(34, 34, 34)
                .addComponent(profilePaneExitBtn)
                .addGap(97, 97, 97))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilePaneExitBtn)
                    .addComponent(profilePaneLogoutBtn)
                    .addComponent(profilePanegoHomeBtn))
                .addGap(64, 64, 64))
        );

        mainTabbedPane.addTab("Profile", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTaskBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(frame);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
                writer.println(addTaskTextArea.getText());
                JOptionPane.showMessageDialog(frame, "Data saved to file: " + file.getAbsolutePath());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_saveTaskBtnActionPerformed

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void profilePaneExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePaneExitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePaneExitBtnActionPerformed

    private void profilePanegoHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePanegoHomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePanegoHomeBtnActionPerformed

    private void addTasksExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTasksExitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTasksExitBtnActionPerformed

    private void addTaskViewTasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskViewTasksBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTaskViewTasksBtnActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton deltaskBtn;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton addTaskgoHome;
    private javax.swing.JButton addTaskViewTasksBtn;
    private javax.swing.JButton profilePaneExitBtn;
    private javax.swing.JButton profilePaneLogoutBtn;
    private javax.swing.JButton profilePanegoHomeBtn;
    private javax.swing.JButton viewTasksExitBtn;
    private javax.swing.JButton viewTasksLogoutBtn;
    private javax.swing.JButton viewTasksgoHomeBtn;
    private javax.swing.JButton addTasksLogoutBtn;
    private javax.swing.JButton addTasksExitBtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel addTaskPanel;
    private javax.swing.JPanel viewTasksPane;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea addTaskTextArea;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton viewTasksAddTaskBtn;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton saveTaskBtn;
    private javax.swing.JButton seeProfileButton;
    private javax.swing.JLabel task1Lbl;
    private javax.swing.JLabel task2Lbl;
    private javax.swing.JLabel task3Lbl;
    private javax.swing.JLabel task4Lbl;
    private javax.swing.JButton viewTasksButton;

    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        if(actionEvent.getSource() == logoutBtn || actionEvent.getSource() == addTasksLogoutBtn || actionEvent.getSource() == viewTasksLogoutBtn || actionEvent.getSource() == profilePaneLogoutBtn) {
            frame.switchPanel(new Login(frame));
        } else if (actionEvent.getSource() == exitButton || actionEvent.getSource() == addTasksExitBtn || actionEvent.getSource() == viewTasksExitBtn || actionEvent.getSource() == profilePaneExitBtn){
            System.exit(0);
        } else if (actionEvent.getSource() == addTaskButton) {
            mainTabbedPane.setSelectedComponent(addTaskPanel);
        } else if (actionEvent.getSource() == viewTasksButton) {
            mainTabbedPane.setSelectedComponent(viewTasksPane);
        } else if (actionEvent.getSource() == seeProfileButton) {
            mainTabbedPane.setSelectedComponent(jPanel4);
        } else if (actionEvent.getSource() == deltaskBtn) {
            addTaskTextArea.setText("");
        } else if (actionEvent.getSource() == addTaskgoHome || actionEvent.getSource() == viewTasksgoHomeBtn || actionEvent.getSource() == profilePanegoHomeBtn) {
            mainTabbedPane.setSelectedComponent(homePanel);
        } else if (actionEvent.getSource() == addTaskViewTasksBtn) {
            mainTabbedPane.setSelectedComponent(viewTasksPane);
        } else if (actionEvent.getSource() == viewTasksAddTaskBtn) {
            mainTabbedPane.setSelectedComponent(addTaskPanel);
        }

    }
    // End of variables declaration//GEN-END:variables
}
