/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project2.taskmaster;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author user85
 */
public class Login extends javax.swing.JPanel {
    MainFrame frame;
    DatabaseHandler database;
    javax.swing.JTextField usernameTextField;
    javax.swing.JPasswordField passwordTextField;
    private String usernameFromLogin;
    private String passwordFromLogin;

    public String getPasswordFromLogin() {
        return passwordFromLogin;
    }
    public String getUsernameFromLogin() {
        return usernameFromLogin;
    }

    /**
     * Creates new form Login
     */
    public Login(MainFrame frame) {
        this.frame = frame;
        database = new DatabaseHandler();
        database.createTable();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JLabel headingLbl = new javax.swing.JLabel();
        javax.swing.JLabel sloganLbl = new javax.swing.JLabel();
        javax.swing.JLabel usrnameLbl = new javax.swing.JLabel();
        javax.swing.JLabel passwordLbl = new javax.swing.JLabel();
        javax.swing.JButton loginBtn = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        signupTxtLbl = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        headingLbl.setFont(new java.awt.Font("Ubuntu Mono", Font.BOLD, 36)); // NOI18N
        headingLbl.setText("Task Master");
        headingLbl.setToolTipText("");

        sloganLbl.setFont(new java.awt.Font("Source Sans Pro Light", Font.ITALIC, 14)); // NOI18N
        sloganLbl.setText("Become a slave of the system");

        usrnameLbl.setText("username");
        passwordLbl.setText("password");

        loginBtn.setText("Login");
        loginBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                loginBtn.setForeground(Color.CYAN);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                loginBtn.setForeground(Color.WHITE);
            }
        });
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        signupTxtLbl.setText("Dont have an account? Sign up");
        signupTxtLbl.setForeground(Color.CYAN);
        //on hover change color of label
        signupTxtLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                signupTxtLbl.setForeground(Color.BLUE);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseEntered(e);
                signupTxtLbl.setForeground(Color.CYAN);
            }
            @Override
            public void mousePressed(MouseEvent e) {
                super.mouseEntered(e);
                frame.switchPanel(new Signup(frame));
            }
        });

        jLabel1.setFont(new java.awt.Font("FreeMono", Font.BOLD, 18)); // NOI18N
        jLabel1.setText("Welcome Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signupTxtLbl)
                    .addComponent(loginBtn))
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(headingLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLbl)
                            .addComponent(usrnameLbl))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sloganLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(headingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sloganLbl)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrnameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLbl)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addGap(109, 109, 109)
                .addComponent(signupTxtLbl)
                .addGap(42, 42, 42))
        );

        usernameTextField.addActionListener(e -> {
            passwordTextField.requestFocusInWindow();
        });

        passwordTextField.addActionListener(e -> {
            loginBtn.doClick();
        });
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        usernameFromLogin = usernameTextField.getText();
        passwordFromLogin = String.valueOf(passwordTextField.getPassword());

        if (areLoginDetailsValid(usernameFromLogin, passwordFromLogin)) {
            frame.switchPanel(new Homepage(frame));
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private boolean areLoginDetailsValid(String usernameFromLogin, String passwordFromLogin) {

        return true;
    }



    javax.swing.JLabel signupTxtLbl;
    // End of variables declaration//GEN-END:variables
}
